### ISSUE TITLE
- Current Issues -

### ISSUE THREAD

**Issue by Vadelius** [Vadelius/swlsimNET#1]
* Add APL examples - preset buttons on import.
* Community needs to make APLs decent, hence Wiki explaining..
* Add gadgets.
* Add more weaponprocs.
* Post 1 iteration to a combatlog on results for debugging *sample timeline*
* Refactor(?)

**Comment by Vadelius** [comment]
Add APL examples - preset buttons on import.
Community needs to make APLs decent, hence Wiki explaining..
Add gadgets.
Add more weaponprocs.
Refactor(?)

**Comment by niklasgs** [comment]
Fixed: 
- Add APL examples - preset buttons on import.
