### ISSUE TITLE
Update readme.

### ISSUE THREAD

**Issue by Vadelius** [Vadelius/swlsimNET#18]

**Comment by harleo** [comment]
Threw something together for you.
I noticed you're hosting the image on Discord, it's not ideal though.
You would want to host the image on the repository itself and then use [Rawgit](https://rawgit.com/) and link that it in the readme.

Hope it helps a little.
[README.txt](https://github.com/Vadelius/swlsimNET/files/1361223/README.txt)

**Comment by Vadelius** [comment]
Thanks @harleo didn't see a PR so updated it myselves!
