### ISSUE TITLE
Parse Results JSON/in localStorage => Charts.

### ISSUE THREAD

**Issue by Vadelius** [Vadelius/swlsimNET#53]
Results now end up in local storage. (Replicate via using Hammer preset > clicking start)
Populate to replicate old design in readme.

Old population of charts: https://hastebin.com/pohemozupu.scala
Picture of rendered view: https://camo.githubusercontent.com/d6f19c93df4451e2df7ca4356ab12a3294710b09/68747470733a2f2f63646e2e7261776769742e636f6d2f566164656c6975732f73776c73696d4e45542f61663265393965642f7265706f73706c6173682e706e67

Results string pretty printed: https://gist.github.com/Vadelius/57eb61614f9d94a813dfa19582d0f828

Linechart uses time for labels. Line chart 1 users penergy/senergy for the 2 datasets - Linechart 2 uses pgimmick/sgimmick for its 2 datasets

**Comment by mdew192837** [comment]
Can you explain a little more in detail of what you want? @Vadelius

**Comment by Vadelius** [comment]
@mdew192837 localStorage.getItem("Results"); will contain the ~ 1200 lines string of json (https://gist.github.com/Vadelius/57eb61614f9d94a813dfa19582d0f828) - data is dyanmic though, only thing that will probably never change with is the timestamps.

**Comment by Vadelius** [comment]
Not sure how long a JSON(parse) can take it.

**Comment by Vadelius** [comment]
Done
