### ISSUE TITLE
Display every second in Energy/Gimmick Timeline

### ISSUE THREAD

**Issue by niklasgs** [Vadelius/swlsimNET#64]
Display every second in Energy/Gimmick Timeline.
As seen in picture below we have to take only some values since there is no room for more.

Can this be solved in a nice way? Zooming in shows more values and zooming out less maybe?

To get data for every second remove IF statement in Report.cs line 105.
"if (lastChangeTimeStamp == 0 || lastChangeTimeStamp + interval < rr.TimeSec)"

![](https://i.gyazo.com/31eb8cf5d05f22e5dcc368438ea33903.png)

**Comment by Vadelius** [comment]
Zooming not possible with current framework. I added for every second and normalized t.
